// <auto-generated />
using System;
using Guilherme.LojaVirtualApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guilherme.LojaVirtualApi.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<long>("CategoriesId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductsId")
                        .HasColumnType("bigint");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("category-products");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("block");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("complement");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zipCode");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.ToTable("addresses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Block = "Jardim",
                            CityId = 1L,
                            Complement = "Apto 203",
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 293, DateTimeKind.Local).AddTicks(3994),
                            CustomerId = 1L,
                            Number = "300",
                            Street = "Rua das Flores",
                            ZipCode = "382220834"
                        },
                        new
                        {
                            Id = 2L,
                            Block = "Centro",
                            CityId = 2L,
                            Complement = "Sala 800",
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 293, DateTimeKind.Local).AddTicks(4137),
                            CustomerId = 1L,
                            Number = "105",
                            Street = "Avenida Matos",
                            ZipCode = "38777012"
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 291, DateTimeKind.Local).AddTicks(4992),
                            Name = "Informatica"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 291, DateTimeKind.Local).AddTicks(5034),
                            Name = "Escritorio"
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(9713),
                            Name = "Uberlândia",
                            StateId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(9774),
                            Name = "São Paulo",
                            StateId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(9778),
                            Name = "Campinas",
                            StateId = 2L
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = "36378912377",
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 291, DateTimeKind.Local).AddTicks(7766),
                            CustomerType = 0,
                            Email = "maria@gmail.com",
                            Name = "Maria Silva"
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<long>("DeliveryAddressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(199),
                            CustomerId = 1L,
                            Date = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryAddressId = 1L,
                            PaymentId = 0L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(302),
                            CustomerId = 1L,
                            Date = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryAddressId = 2L,
                            PaymentId = 0L
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("orderId");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productId");

                    b.Property<double>("Discount")
                        .HasColumnType("float")
                        .HasColumnName("discount");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("order-Items");

                    b.HasData(
                        new
                        {
                            OrderId = 1L,
                            ProductId = 1L,
                            Discount = 0.0,
                            Price = 2000.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 1L,
                            ProductId = 3L,
                            Discount = 0.0,
                            Price = 80.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 2L,
                            ProductId = 2L,
                            Discount = 0.0,
                            Price = 800.0,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("paymentStatus");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("payments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Payment");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 289, DateTimeKind.Local).AddTicks(9399),
                            Name = "Computador",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 291, DateTimeKind.Local).AddTicks(3762),
                            Name = "Impressora",
                            Price = 800.0
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 291, DateTimeKind.Local).AddTicks(3796),
                            Name = "Mouse",
                            Price = 80.0
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("states");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(8007),
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(8042),
                            Name = "São Paulo"
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Telephone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("telephones");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(6868),
                            CustomerId = 1L,
                            Number = "27363323"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(6919),
                            CustomerId = 1L,
                            Number = "27363323"
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.PaymentWithBillet", b =>
                {
                    b.HasBaseType("Guilherme.LojaVirtualApi.Models.Entities.Payment");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dueDate");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payDate");

                    b.HasDiscriminator().HasValue("PaymentWithBillet");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(5157),
                            OrderId = 2L,
                            PaymentStatus = 0,
                            DueDate = new DateTime(2021, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.PaymentWithCard", b =>
                {
                    b.HasBaseType("Guilherme.LojaVirtualApi.Models.Entities.Payment");

                    b.Property<int>("Installments")
                        .HasColumnType("int")
                        .HasColumnName("installments");

                    b.HasDiscriminator().HasValue("PaymentWithCard");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2021, 8, 11, 0, 20, 15, 292, DateTimeKind.Local).AddTicks(3296),
                            OrderId = 1L,
                            PaymentStatus = 1,
                            Installments = 6
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Address", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.City", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Order", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Product", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Payment", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Guilherme.LojaVirtualApi.Models.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Telephone", b =>
                {
                    b.HasOne("Guilherme.LojaVirtualApi.Models.Entities.Customer", null)
                        .WithMany("Telephones")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Telephones");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.Product", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Guilherme.LojaVirtualApi.Models.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
